[package]
name = 'Econia'
version = '3.0.0' # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia = 'e56148c106146758a4172a7189cd8487f84997de6f6c2b3396106a8f82cb0c33'
# Mock users for unit tests
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = '971c160079263a8d3e1d2503a570b01ecaaf10ba'
